add workflow
Signed-off-by: yifengyou <842056007@qq.com>

diff --git a/.github/workflows/multi-build-eaidk610.yml b/.github/workflows/multi-build-eaidk610.yml
--- a/.github/workflows/multi-build-eaidk610.yml
+++ b/.github/workflows/multi-build-eaidk610.yml
@@ -1,26 +1,109 @@
 #==========================================================================
 # Description: Build Armbian
-# Copyright (C) 2025 https://github.com/yifengyou/nanopit4
+# Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
 #==========================================================================
 
-name: Multibuild EAIDK-610 armbian
+name: Build EAIDK-610 armbian
 
 on:
   repository_dispatch:
-  workflow_dispatch: # 支持手动触发并交互式选择参数（如选择 Ubuntu 版本 jammy/noble 等）
+  workflow_dispatch:
     inputs:
+      set_release:
+        description: "Select OS Release."
+        required: false
+        default: "bullseye"
+        type: choice
+        options:
+          - bullseye
+          - jammy
+          - noble
+          - bookworm
       armbian_board:
         description: "Select device board."
         required: false
         default: "eaidk-610"
         type: choice
         options:
-          - all
+          - smart-am60
           - eaidk-610
+          - fine3399
           - firefly-rk3399
           - fmx1-pro
-          - nanopct4
-          - nanopct6
+          - h88k
+          - h88k-v3
+          - king3399
+          - kylin3399
+          - nanopc-t6
+          - nanopi-r5c
+          - nanopi-r5s
+          - orangepi-5-plus
+          - rock5b
+          - rock5c
+          - tn3399
+      armbian_kernel:
+        description: "Select kernel version."
+        required: false
+        default: "6.1.y_6.12.y"
+        type: choice
+        options:
+          - 5.4.y
+          - 5.10.y
+          - 5.15.y
+          - 6.1.y
+          - 6.6.y
+          - 6.12.y
+          - 5.4.y_5.10.y
+          - 5.15.y_6.1.y
+          - 6.1.y_6.12.y
+          - 6.1.y_6.6.y
+          - 6.6.y_6.12.y
+      auto_kernel:
+        description: "Auto use the latest kernel."
+        required: false
+        default: true
+        type: boolean
+      kernel_repo:
+        description: "Set the kernel repository."
+        required: false
+        default: "ophub/kernel"
+        type: choice
+        options:
+          - ophub/kernel
+      kernel_usage:
+        description: "Set the tags of the stable kernel."
+        required: false
+        default: "stable"
+        type: choice
+        options:
+          - stable
+          - flippy
+          - dev
+          - beta
+      armbian_fstype:
+        description: "Select armbian rootfs type."
+        required: false
+        default: "ext4"
+        type: choice
+        options:
+          - ext4
+          - btrfs
+      armbian_storage:
+        description: "Select image storage type."
+        required: false
+        default: "save"
+        type: choice
+        options:
+          - save
+          - temp
+      builder_name:
+        description: "Set Armbian builder signature."
+        required: false
+        default: "ophub"
+        type: choice
+        options:
+          - ophub
+          - angel
 
 env:
   TZ: America/New_York
@@ -31,25 +114,41 @@ jobs:
     runs-on: ubuntu-22.04
     if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
 
-    strategy:
-      matrix:
-        set_release:
-          - bookworm
-          - bullseye
-          - buster
-          - focal
-          - jammy
-          - noble
-          - oracular
-          - plucky
-          - sid
-          - trixie
-      fail-fast: false
-      max-parallel: 10
-
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
+      - name: check GITHUB_TOKEN
+        id: check_token
+        run: |
+          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
+            echo "GITHUB_TOKEN not set, abort"
+            exit 1
+          else
+            echo "GITHUB_TOKEN already set."
+          fi
+          cat /proc/cpuinfo > envinfo.txt
+          df -h >> envinfo.txt
+          lsblk >> envinfo.txt
+          free -w -h >> envinfo.txt
+          cat /etc/*release >> envinfo.txt
+
+      - name: test GITHUB_TOKEN
+        uses: ncipollo/release-action@main
+        if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
+        with:
+          tag: "workflow_envinfo"
+          artifacts: envinfo.txt
+          allowUpdates: true
+          removeArtifacts: false
+          replacesArtifacts: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+          body: |
+            ### Github Workflow environment info gather
+            - cpuinfo
+            - disk info
+            - memory info
+            - os release info
 
       - name: Initialization environment
         id: init
@@ -98,29 +197,68 @@ jobs:
         run: |
           df -hT ${PWD}
           git clone -q --single-branch --depth=1 --branch=main https://github.com/armbian/build.git build
+          ln -sf /builder/build ${GITHUB_WORKSPACE}/build
+          ln -sf /builder/build /home/runner/work/_actions/ophub/amlogic-s9xxx-armbian/main/build
           echo "status=success" >> ${GITHUB_OUTPUT}
 
-      - name: Compile Armbian [ ${{ matrix.set_release }} ]
+      - name: Compile Armbian [ ${{ inputs.set_release }} ]
         id: compile
         working-directory: /builder
         if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
         run: |
           # Compile method and parameter description: https://docs.armbian.com/Developer-Guide_Build-Options
-          echo "build_tag=Armbian_${{ inputs.armbian_board }}_${{ matrix.set_release }}" >> ${GITHUB_OUTPUT}
           cd build/
-              ./compile.sh RELEASE=${{ matrix.set_release }} BOARD=${{ inputs.armbian_board }} BRANCH=current BUILD_MINIMAL=no \
+              ./compile.sh RELEASE=${{ inputs.set_release }} BOARD=odroidn2 BRANCH=current BUILD_MINIMAL=no \
                            BUILD_ONLY=default HOST=armbian BUILD_DESKTOP=no EXPERT=yes KERNEL_CONFIGURE=no \
-                           COMPRESS_OUTPUTIMAGE="sha,img,xz" SHARE_LOG=yes
-          ls -alh /builder/build/output/images/
+                           COMPRESS_OUTPUTIMAGE="sha" SHARE_LOG=yes
           echo "status=success" >> ${GITHUB_OUTPUT}
 
+      - name: Organize files and clear space
+        id: clean
+        if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
+        run: |
+          git clone -q --single-branch --depth=1 --branch=main https://github.com/ophub/amlogic-s9xxx-armbian.git amlogic-s9xxx-armbian.git
+          cp -a amlogic-s9xxx-armbian.git/compile-kernel .
+          ls -alh
+          find . -name "*.img"
+          # Organize and keep essential files, delete unnecessary files
+          chmod +x ${ROOTFS_SCRIPT}
+          ${ROOTFS_SCRIPT} -v ${{ inputs.set_release }}
+          # Output cleaning result information
+          df -hT ${PWD}
+          echo "build_tag=Armbian_${{ inputs.armbian_board }}_${{ inputs.set_release }}" >> ${GITHUB_OUTPUT}
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Upload Armbian image to Release
         uses: ncipollo/release-action@main
-        if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
+        if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
         with:
-          tag: ${{ steps.compile.outputs.build_tag }}
-          artifacts: /builder/build/output/images/*
+          tag: ${{ steps.clean.outputs.build_tag }}
+          artifacts: build/output/images/*
+          allowUpdates: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Rebuild Armbian
+        uses: ophub/amlogic-s9xxx-armbian@main
+        if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
+        with:
+          # call action.yml in ophub/amlogic-s9xxx-armbian@main
+          build_target: armbian
+          armbian_path: build/output/images/*.img.gz
+          armbian_board: ${{ inputs.armbian_board }}
+          armbian_kernel: ${{ inputs.armbian_kernel }}
+          auto_kernel: ${{ inputs.auto_kernel }}
+          kernel_repo: ${{ inputs.kernel_repo }}
+          kernel_usage: ${{ inputs.kernel_usage }}
+          armbian_fstype: ${{ inputs.armbian_fstype }}
+          builder_name: ${{ inputs.builder_name }}
+
+      - name: Upload Rebuild image to Release
+        uses: ncipollo/release-action@main
+        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
+        with:
+          tag: ${{ steps.clean.outputs.build_tag }}
+          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
           removeArtifacts: false
           replacesArtifacts: true
